### ISSUE TITLE
cell arrangement

### ISSUE THREAD

**Issue by classofoutcasts** [chrisabird/pack-builder#2]
Hi Chris,

First of all, really appreciate the efforts you've made to setup repackr.com, it's great!
I do have a question though regarding the arrangement of cells. there's something I don't really understand.

Let's say, for example, I want to build a 4s6P battery and have these capacity cells:

4 x 500 mAh
4 x 1000 mAh
4 x 1500 mAh
4 x 2000 mAh
4 x 2500 mAh
4 x 3000 mAh

I would manually arrange it like this:

3000 3000 3000 3000
2500 2500 2500 2500
2000 2000 2000 2000
1500 1500 1500 1500
1000 1000 1000 1000
500 500 500 500

Repackr.com arranges it like below and I don't really understand why it does it like that:

3000 2500 2500 3000
3000 2000 2500 3000
1500 2000 2000 2500
1500 2000 1500 1000
1000 1000 1500 500
500 1000 500 500

Is this a better way to arrange the cells because of deviation than the first manual arrangement?

Hope you can shed a light on it as I'd really like to understand the best way to arrange my packs..

**Comment by chrisabird** [comment]
There is now an FAQ page on the site to try make this information available to all.
